apiVersion: skaffold/v4beta10
kind: Config
metadata:
  name: outyet
deploy:
  helm:
    releases:
      - name: outyet
        createNamespace: true
        namespace: app
        chartPath: helm
        valuesFiles:
          - helm/values.yaml
